version: '2'
services:
    coolapp-app:
        image: coolapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://coolapp-mysql:3306/coolapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    coolapp-mysql:
        extends:
            file: mysql.yml
            service: coolapp-mysql
